/// Flutter icons PokeDima
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PokeDima
///      fonts:
///       - asset: fonts/PokeDima.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PokeDima {
  PokeDima._();

  static const _kFontFam = 'PokeDima';
  static const String? _kFontPkg = null;

  static const IconData pokemon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cards = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scanner = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData personal = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
